### ISSUE TITLE
Interactive footnote tooltips

### ISSUE THREAD

**Issue by davidheyman** [axismaps/evolution-of-risk#1]

**Comment by awoodruff** [comment]
Is this tooltip meant to be on click or on mouseover? If the latter, does clicking jump to the footnote at the bottom, à la Wikipedia? Also, what (if any) would be the touch behavior? cc @bcsheesley

**Comment by davidheyman** [comment]
Display on hover, jump to footnote on click. As for touch, tap once to display, tap again to jump?

**Comment by bcsheesley** [comment]
That works for me!

On Tue, Jun 23, 2015 at 9:17 AM, David Heyman notifications@github.com
wrote:

> Display on hover, jump to footnote on click. As for touch, tap once to
> display, tap again to jump?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/axismaps/evolution-of-risk/issues/1#issuecomment-114520116
> .

## 

---

Ben Sheesley
ben@axismaps.com
(254) 722-8014

Axis Maps LLC

## http://www.axismaps.com

**Comment by awoodruff** [comment]
Thanks guys. The obnoxiousness of the iPad works in favor of that tap behavior!
