### ISSUE TITLE
Data probing on D3 maps

### ISSUE THREAD

**Issue by davidheyman** [axismaps/evolution-of-risk#12]

**Comment by awoodruff** [comment]
Forgot to mention it, but I put in a probes commit the other day. Just a basic name/value thing. Does this look okay?
![screen shot 2015-05-28 at 3 36 48 pm](https://cloud.githubusercontent.com/assets/3533462/7869249/77a36dbe-054f-11e5-8b36-033836480d25.png)
![screen shot 2015-05-28 at 3 36 55 pm](https://cloud.githubusercontent.com/assets/3533462/7869250/77a45fc6-054f-11e5-9296-f823b998ff2f.png)

**Comment by davidheyman** [comment]
Yep. Looks great. Thanks.
