### ISSUE TITLE
Links in footnotes

### ISSUE THREAD

**Issue by davidheyman** [axismaps/evolution-of-risk#14]
1. Do you know what the appropriate style is for hyperlinks here? Can we truncate them if they're active links?
2. Should the footnote hover stay for a little bit so you can click on the link? I guess you can click the footnote to go to the bottom of the page but I don't know how self-explanatory that is.

**Comment by kingfisher13** [comment]
3224404be4255d94a643c69953544695e646744d should solve 2.

**Comment by kingfisher13** [comment]
Footnote needs to disappear if you are hovering over a separate footnote. Right now, it runs the full Timeout first.
