### ISSUE TITLE
Video alignment on iPad

### ISSUE THREAD

**Issue by davidheyman** [axismaps/evolution-of-risk#18]
Off-center in relation to page and a few pixels gap between video and controls

![file 26-06-2015 14 46 51](https://cloud.githubusercontent.com/assets/791434/8378543/42094fdc-1c12-11e5-83a5-be979a498764.png)

**Comment by kingfisher13** [comment]
I couldn't replicate the couple of pixels too wide, but the off-center issue is now fixed.

**Comment by awoodruff** [comment]
I'm not seeing this either.

**Comment by davidheyman** [comment]
This got fixed by something else
