### ISSUE TITLE
Header flickers up and down during fast scrolling

### ISSUE THREAD

**Issue by davidheyman** [axismaps/evolution-of-risk#19]

**Comment by kingfisher13** [comment]
@davidheyman I can't reproduce this. What are you seeing and on what device/comp?

**Comment by davidheyman** [comment]
I think it might be an issue with Macs only. Something about how they've implemented smooth scrolling. Maybe Andy can replicate it.

**Comment by awoodruff** [comment]
I definitely was noticing this the other day, but now I don't see it. Maybe there was a magic accidental fix somewhere?

**Comment by davidheyman** [comment]
Yep. Gone for me too!
