### ISSUE TITLE
Static legends

### ISSUE THREAD

**Issue by davidheyman** [axismaps/evolution-of-risk#2]

**Comment by awoodruff** [comment]
Does this mean legends for the flooding, urban, etc. maps?

**Comment by davidheyman** [comment]
Yep. There are designs for these on Avocode.

**Comment by awoodruff** [comment]
Is there any content for the "Sources" bit from the design?
![screen shot 2015-06-23 at 11 35 25 am](https://cloud.githubusercontent.com/assets/3533462/8310106/024031b8-199c-11e5-99a2-03ac08bb473a.png)
