### ISSUE TITLE
Iframe playback crashes Safari

### ISSUE THREAD

**Issue by davidheyman** [axismaps/evolution-of-risk#31]
This only happens in the online version. Safari crashes in 1976.

**Comment by awoodruff** [comment]
I'm not getting this one... wonder if the small changes for #34 will help?

**Comment by davidheyman** [comment]
I'm still getting it. Still only online and still only with Safari 8.0.7. It looks like 1976 isn't the issue but it crashes after playing a certain number of frames.

**Comment by awoodruff** [comment]
Huh, yeah I see it now. I have no earthly idea what's going on, but it seems to occur only under pretty specific circumstances: only in a newer version of Safari, only if playback is triggered by scroll and not by click—and now, it seems, only if the dev tools are open. No idea if the couple of small changes I just made had any impact on that, but can you give it a try making sure you don't have the console or dev tools open? For me so far it's reliably working with them closed and reliably crashing with them open.

**Comment by davidheyman** [comment]
Now it's not loading for me at all in Safari. Maybe it's a bug in the new version?

**Comment by awoodruff** [comment]
Forgot to follow up on this the other day! I updated to 8.0.7 and still wasn't getting a crash (again, without any dev tools open). Computers are ridiculous.

**Comment by davidheyman** [comment]
Maybe try using `<object>` instead of the iframe? This crash is very consistent for me.

**Comment by davidheyman** [comment]
![evolution_of_risk](https://cloud.githubusercontent.com/assets/791434/8524412/01bee7b4-23f3-11e5-9be2-18f75499a5d4.jpg)

It always looks like this and crashes as soon as I scroll to it.

**Comment by awoodruff** [comment]
Despite it working the other day, today I got the original type of crash (at 1976). Now after messing with some number precision it's behaving better again, but who knows. See what happens on your end now when you get a chance.

**Comment by davidheyman** [comment]
It loads! ...but it bonks out at 1965 for me. I think we have to take them out of their iframes and put them in index.html. Are there any terrible conflicts with doing that?

**Comment by awoodruff** [comment]
1965, eh? 2002 was my year for a while. Anyway, not too hard to wrap all the code in a function to prevent conflicts. I just put up a quick and pretty dirty version of this where the pie chart map is inserted directly into the page. Give it a whirl and if it works I'll clean it up and get the other map in there too.

**Comment by davidheyman** [comment]
Works like a charm. Hopefully next time we'll remember that iframes create as many problems as they solve.

Side note: I got some weird 504 errors when loading d3.js. Maybe move those local so we're not depending on their CDN for this?
