### ISSUE TITLE
IE11 - Title font isn't rendering in Unit

### ISSUE THREAD

**Issue by davidheyman** [axismaps/evolution-of-risk#35]
![screenshot_6_30_15__3_15_pm](https://cloud.githubusercontent.com/assets/791434/8432943/f764f70c-1f3a-11e5-9091-c6997fa92c03.jpg)

**Comment by awoodruff** [comment]
Is this not Unit? It looks the same as Chrome, etc. other than small differences in how they handle the weight.

**Comment by davidheyman** [comment]
Yeah. Looks like it is just weight. Can that be standardized?

**Comment by awoodruff** [comment]
I think so, mostly... it's mainly the section title ("introduction") that looks different, right? That's a matter of being explicit about h1 font weight.

I actually like the IE weight (400 probably), or maybe a semibold, a little better than bold of Chrome et al. Is that crazy?

**Comment by davidheyman** [comment]
![title](https://cloud.githubusercontent.com/assets/791434/8441396/c8743fb8-1f6f-11e5-8127-0df71baac7dd.png)

I'm on team 700 (the 700 Club?) but I think thinner works well for the first screen where there's the title as well.

**Comment by awoodruff** [comment]
That last commit makes it bold for everything except Introduction, which is 500. Cool?
