### ISSUE TITLE
[FF] Styling of footnote probes gets messed up after clicking on the footnote

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/evolution-of-risk#46]
These look normal when hovering the first time, but if you click the orange box and then hover, the probe background becomes semitransparent like this:

<img width="901" alt="screen shot 2016-01-04 at 10 22 37 pm" src="https://cloud.githubusercontent.com/assets/4501388/12107551/237cdcfc-b332-11e5-9171-936e4722d5cf.png">

**Comment by kingfisher13** [comment]
FF doesn't jump down to reference list on click.
Chrome jumps, but has the same transparent background issue if you scroll back up and hover after a click.
