### ISSUE TITLE
Reset the playhead when moving to a new tab

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/evolution-of-risk#47]
I moved to Venezuela while the China movie was playing and expected the playhead to move back to the beginning. 

<img width="1028" alt="screen shot 2016-01-04 at 10 31 43 pm" src="https://cloud.githubusercontent.com/assets/4501388/12107631/4562c2b8-b333-11e5-8858-99f40a19ca2f.png">

**Comment by kingfisher13** [comment]
@bcsheesley I'm getting the expected behavior (goes back to beginning on tab switch). Any further details on this?

**Comment by bcsheesley** [comment]
In Safari, when I switch tabs, there's a pause in which I get a screen with a big play button like the one posted above. After a second, this automatically disappears and the new movie starts from the beginning.

In FF, when I switch, I get the play button screen, but the movie doesn't automatically start. This is where I got confused, because the movie shows the first year (1992), but the playhead is positioned at its last location from another tab. Pressing play will reset the playhead to the beginning, so that is working.

Maybe this isn't a big deal. Or maybe, if possible, movies should automatically play when switching tabs in FF. I'm happy to go with what you think is best.
