### ISSUE TITLE
Reset movies when they are scrolled far out of view

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/evolution-of-risk#54]
I scrolled to the end of the page and back to the beginning to find that all my movies were playing. Is there a way to return these to their inactive state once scrolling past them? Not sure if there's any performance improvement in doing that as well.

**Comment by awoodruff** [comment]
I haven't tested this much, but have you found this to happen with the interactive maps too? (A quick look had them pausing if you scroll beyond, but I've only looked at Chrome.) Those maps do seem to have a potential performance effect in some browsers.

**Comment by bcsheesley** [comment]
Yep, with the interactive maps, I also have them pausing when you scroll beyond. And if you scroll above they will play to the end and stop. That seems fine to me.

**Comment by bcsheesley** [comment]
Update: this looks okay to me now. From what I can tell, when you scroll away from the movies they play to the end and stop. They start again when you scroll back to them.
